// Real banner library — 141 high-quality designed images organized by pillar.
// Manifest is generated by scripts/process-creatives.mjs which compresses + uploads
// the source PNGs to R2 and emits this JSON.

import manifest from "./creatives-manifest.json";

export type CreativePalette = { from: string; via: string; to: string };

export type CreativeBanner = {
  slug: string;
  url: string;
  categoryId: string;
  categoryLabel: string;
  emoji: string;
  palette: CreativePalette;
  original: string;
};

export type CreativeCategoryDef = {
  id: string;
  label: string;
  emoji: string;
  description: string;
  count: number;
};

export const ALL_CREATIVES: CreativeBanner[] = manifest.items as CreativeBanner[];

const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  mythbuster: "Common DeFi myths debunked with on-chain proof.",
  product: "Deep-dive product visuals from the Turbo Loop bible.",
  quickstart: "Step-by-step starter visuals for new users.",
  "p1-math": "The math behind sustainable, transparent yield.",
  "p2-psychology": "How ownership and trust shape every deposit.",
  "p3-multiplier": "Twenty levels deep — how networks compound.",
  "p4-risk": "Risk management for serious DeFi participants.",
  "p5-velocity": "The compounding curve in motion.",
  "p6-trust": "Trustless contracts, verifiable from any browser.",
  "p7-arbitrage": "Borderless capital — global yield arbitrage.",
  "p8-legacy": "Legacy and inheritance in a permissionless world.",
  "p9-inflation": "Stablecoin yield as an inflation shield.",
  "p10-ethics": "Leadership ethics in decentralized communities.",
};

/**
 * Distinct categories ordered for display. Each has a count of how many banners
 * fall under it. Used to render the filter pill bar.
 */
export const CREATIVE_CATEGORIES: CreativeCategoryDef[] = Array.from(
  new Map(
    ALL_CREATIVES.map((c) => [
      c.categoryId,
      {
        id: c.categoryId,
        label: c.categoryLabel,
        emoji: c.emoji,
        description: CATEGORY_DESCRIPTIONS[c.categoryId] || "",
        count: 0,
      },
    ])
  ).values()
).map((cat) => ({
  ...cat,
  count: ALL_CREATIVES.filter((c) => c.categoryId === cat.id).length,
}));

// Sort categories: pillars 1-10 first by number, then mythbuster/product/quickstart
const SORT_ORDER: string[] = [
  "p1-math", "p2-psychology", "p3-multiplier", "p4-risk", "p5-velocity",
  "p6-trust", "p7-arbitrage", "p8-legacy", "p9-inflation", "p10-ethics",
  "mythbuster", "product", "quickstart",
];
CREATIVE_CATEGORIES.sort((a, b) => SORT_ORDER.indexOf(a.id) - SORT_ORDER.indexOf(b.id));

/** Get banners for a given category id, or all if id === "all" */
export function bannersForCategory(id: string): CreativeBanner[] {
  if (id === "all") return ALL_CREATIVES;
  return ALL_CREATIVES.filter((c) => c.categoryId === id);
}
