// /faq — frequently asked questions. Static, accordion-free (just plain
// HTML <details> for zero JS interactivity).

import type { Metadata } from "next";
import { Container } from "@components/ui/Container";
import { PageHero } from "@components/layout/PageHero";

export const metadata: Metadata = {
  title: "FAQ — Common Questions About TurboLoop",
  description:
    "What is TurboLoop? Where does the yield come from? Is it safe? How do I start? Plain answers, no fluff.",
  alternates: { canonical: "https://turboloop.tech/faq" },
};

const FAQS: Array<{ category: string; items: Array<{ q: string; a: string }> }> = [
  {
    category: "Getting started",
    items: [
      {
        q: "What is TurboLoop?",
        a: "TurboLoop is a decentralized yield protocol on Binance Smart Chain. You deposit stablecoins, the smart contract deploys them into PancakeSwap V3 liquidity positions, and you earn yield from real trading fees — up to 54% annually. There is no team-managed treasury, no admin key, no upgrade mechanism. The contract executes itself.",
      },
      {
        q: "How do I start?",
        a: "Connect MetaMask or Trust Wallet to the dApp at turboloop.io. Buy USDT or BNB through Turbo Buy (fiat-to-crypto inside the same site, or use any exchange). Deposit USDT into the farming contract. Yield begins generating immediately.",
      },
      {
        q: "What's the minimum deposit?",
        a: "$50 USDT. We deliberately kept it low so anyone can participate, regardless of income.",
      },
    ],
  },
  {
    category: "Yield + math",
    items: [
      {
        q: "Where does the yield actually come from?",
        a: "Three real revenue sources: (1) PancakeSwap V3 trading fees from every swap that touches our liquidity positions — typically 0.3% per trade. (2) Turbo Swap fees from in-app token swaps. (3) Turbo Buy fees from fiat-to-crypto on-ramps. All three are external revenue, not new deposits. This is what makes it not a Ponzi.",
      },
      {
        q: "Is 54% APY guaranteed?",
        a: "No — yield is variable. 54% is the engineered target based on PancakeSwap V3 trading volume + concentrated liquidity ranges. In high-volume periods it goes higher; in low-volume periods, lower. Every yield distribution is recorded on-chain — you can verify historicals at any time.",
      },
      {
        q: "What if no one new joins TurboLoop?",
        a: "Yield still flows. Trading fees come from the broader BSC market — millions of trades per day across PancakeSwap. As long as PancakeSwap exists and people swap tokens, the LP positions earn fees. New TurboLoop members are not required to sustain yield.",
      },
    ],
  },
  {
    category: "Security",
    items: [
      {
        q: "Is TurboLoop safe?",
        a: "Audited by Haze Crypto (independent firm, public report). Ownership renounced on-chain (no admin key). 100% LP locked through Unicrypt. Source verified on BscScan. $100K bounty for anyone who can find a centralization risk. We removed every way we could harm you.",
      },
      {
        q: "Could the team rug pull?",
        a: "No. The team has zero contract control: ownership is renounced (mechanically destroyed on-chain). LP is locked through a third-party contract. No upgrade path exists. Even if the team wanted to harm holders, the math says they cannot.",
      },
      {
        q: "What if PancakeSwap fails?",
        a: "PancakeSwap has been the largest DEX on BSC since 2020 with multi-billion daily volume. If it ever failed, our LP would still hold the underlying tokens — they're never converted to anything else. You'd recover your stablecoin principal.",
      },
    ],
  },
  {
    category: "Earning + community",
    items: [
      {
        q: "How does the referral network work?",
        a: "20 levels deep. When someone in your network earns yield, you earn an additional bonus — generated by the protocol itself, not deducted from them. Levels 1–10: 5% bonus. Levels 11–20: 10% bonus. Build a real network, earn while you sleep.",
      },
      {
        q: "Can I become a paid creator or presenter?",
        a: "Yes. Apply at /apply for either Creator Star ($10–$100/video based on views) or Local Presenter ($100/month for hosting weekly Zoom sessions). Both pay in stablecoins. Reviewed within 48 hours.",
      },
      {
        q: "Where can I share my story?",
        a: "Submit a testimonial, photo, video, or written story at /submit. Approved submissions get featured on /community and across our channels.",
      },
    ],
  },
];

export default function FAQPage() {
  return (
    <main className="relative pb-12 md:pb-20">
      <PageHero
        eyebrow="Frequently Asked"
        title="Plain answers. No jargon."
        subtitle="The questions we hear most often, in plain English. Can't find what you need? Ask in our Telegram channel."
      />

      <Container width="narrow">
        <div className="space-y-10">
          {FAQS.map(group => (
            <section key={group.category}>
              <h2 className="text-[0.6875rem] font-bold tracking-[0.2em] uppercase text-[var(--c-brand-cyan)] mb-4">
                {group.category}
              </h2>
              <div className="space-y-3">
                {group.items.map(({ q, a }) => (
                  <details
                    key={q}
                    className="group rounded-[var(--r-xl)] bg-[var(--c-surface)] border border-[var(--c-border)] shadow-[var(--s-sm)] overflow-hidden"
                  >
                    <summary className="cursor-pointer list-none p-5 flex items-start justify-between gap-3 font-bold text-[var(--c-text)] hover:text-[var(--c-brand-cyan)] transition-colors">
                      <span>{q}</span>
                      <span
                        className="flex-shrink-0 mt-0.5 text-[var(--c-text-subtle)] group-open:rotate-45 transition-transform"
                        aria-hidden="true"
                      >
                        +
                      </span>
                    </summary>
                    <div className="px-5 pb-5 text-[var(--c-text-muted)] leading-relaxed">
                      {a}
                    </div>
                  </details>
                ))}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-12 text-center text-sm text-[var(--c-text-muted)]">
          Still have a question?{" "}
          <a
            href="https://t.me/TurboLoop_Official"
            target="_blank"
            rel="noopener noreferrer"
            className="font-bold text-[var(--c-brand-cyan)] hover:underline"
          >
            Ask on Telegram →
          </a>
        </div>
      </Container>
    </main>
  );
}
