// /api/creatives/download-kit — redirects to pre-generated R2 zip files.
//
// GET ?category=lifestyle
//
// Zip files are pre-generated by scripts/generate-kits.py and stored at:
//   R2_PUBLIC_URL/kits/{category}.zip
//
// This route just validates the category and redirects to R2.
// Downloads are instant — served directly from R2 CDN, no function bandwidth used.
//
// To regenerate kits after adding new banners:
//   python3 scripts/generate-kits.py [category...]

import { NextRequest } from "next/server";
import { ALL_UNIFIED_CREATIVES } from "@lib/unifiedCreativesData";

export const runtime = "edge";

const R2_PUBLIC_URL = "https://pub-1d13f4e7ccfa4575bc04b75045f1b1b1.r2.dev";

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const category = searchParams.get("category")?.trim();

  if (!category) {
    return new Response(JSON.stringify({ error: "Missing category param" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Validate the category exists in our data
  const exists = ALL_UNIFIED_CREATIVES.some(i => i.categoryId === category);
  if (!exists) {
    return new Response(JSON.stringify({ error: "Category not found" }), {
      status: 404,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Redirect to the pre-generated R2 zip
  const zipUrl = `${R2_PUBLIC_URL}/kits/${category}.zip`;

  return Response.redirect(zipUrl, 302);
}
