// Campaign creative library — 504 images across 12 categories.
// Loaded from /public/campaigns-manifest.json (generated by
// scripts/generate-campaigns-manifest.mjs at upload time).
// Used by /creatives/[category] sub-pages and the Campaign Suite
// section on the main /creatives page.
import manifest from "../public/campaigns-manifest.json";

export type CampaignCreative = {
  category: string;
  filename: string;
  url: string;
  alt: string;
  title: string;
  description: string;
  keywords: string[];
};

export const ALL_CAMPAIGN_CREATIVES: CampaignCreative[] =
  manifest as CampaignCreative[];

// ── Category metadata ──────────────────────────────────────────────────────

export type CampaignCategoryDef = {
  id: string;
  label: string;
  emoji: string;
  description: string;
  /** Short SEO-focused description for sub-page meta */
  metaDescription: string;
  /** Target keyword cluster for this sub-page */
  keywords: string[];
  count: number;
  accent: { from: string; to: string };
};

export const CAMPAIGN_CATEGORIES: CampaignCategoryDef[] = [
  {
    id: "lifestyle",
    label: "Passive Income Lifestyle",
    emoji: "🌴",
    description: "Aspirational banners showing the freedom that passive income creates — beach, coffee, family time, financial independence.",
    metaDescription: "50 free DeFi passive income lifestyle banners for Telegram, WhatsApp, and social media. Download and share — no attribution required.",
    keywords: ["passive income lifestyle", "financial freedom DeFi", "crypto passive income banners"],
    count: 0,
    accent: { from: "#06B6D4", to: "#7C3AED" },
  },
  {
    id: "token",
    label: "$TURBO Token",
    emoji: "🪙",
    description: "Token launch, supply mechanics, vesting schedule, and on-chain transparency banners for $TURBO.",
    metaDescription: "50 free $TURBO token marketing banners — tokenomics, supply, on-chain proof. Download for Telegram and social media.",
    keywords: ["TURBO token banners", "DeFi token marketing", "crypto token launch banners"],
    count: 0,
    accent: { from: "#F59E0B", to: "#EF4444" },
  },
  {
    id: "referral",
    label: "Referral & Affiliate",
    emoji: "🤝",
    description: "20-level affiliate system banners — earn on every level, build your network, grow your passive income.",
    metaDescription: "50 free DeFi referral marketing banners for the TurboLoop 20-level affiliate system. Download and share.",
    keywords: ["DeFi referral marketing banners", "crypto affiliate banners", "20 level referral system"],
    count: 0,
    accent: { from: "#10B981", to: "#06B6D4" },
  },
  {
    id: "objection-handler",
    label: "Objection Handlers",
    emoji: "🛡️",
    description: "FUD-busting banners that address the most common objections — scam concerns, risk questions, sustainability doubts.",
    metaDescription: "50 free DeFi objection handler banners — is it a scam? Is it safe? Answer every question with a shareable image.",
    keywords: ["DeFi objection handler banners", "crypto FUD busting", "is TurboLoop safe"],
    count: 0,
    accent: { from: "#8B5CF6", to: "#EC4899" },
  },
  {
    id: "hindi-new",
    label: "Hindi Market",
    emoji: "🇮🇳",
    description: "Hindi-language banners for the Indian market — passive income, DeFi education, and TurboLoop protocol in Hindi.",
    metaDescription: "50 free Hindi DeFi marketing banners for the Indian market. TurboLoop passive income banners in Hindi.",
    keywords: ["hindi DeFi banners", "hindi passive income", "TurboLoop hindi marketing"],
    count: 0,
    accent: { from: "#F97316", to: "#FBBF24" },
  },
  {
    id: "nigerian",
    label: "Nigerian Market",
    emoji: "🇳🇬",
    description: "Banners tailored for the Nigerian market — local context, familiar references, DeFi education for West Africa.",
    metaDescription: "50 free DeFi marketing banners for the Nigerian market. TurboLoop passive income banners for West Africa.",
    keywords: ["nigeria DeFi banners", "nigeria passive income crypto", "TurboLoop nigeria"],
    count: 0,
    accent: { from: "#22C55E", to: "#16A34A" },
  },
  {
    id: "success-story",
    label: "Success Stories",
    emoji: "🏆",
    description: "First withdrawal moments, debt payoff milestones, and community wins — real proof that the protocol works.",
    metaDescription: "40 free DeFi success story banners — first withdrawals, debt payoff, financial milestones. Share real proof.",
    keywords: ["DeFi success story banners", "crypto passive income proof", "TurboLoop withdrawal"],
    count: 0,
    accent: { from: "#3B82F6", to: "#6366F1" },
  },
  {
    id: "education-defi",
    label: "DeFi Education",
    emoji: "📚",
    description: "Smart contracts, blockchain basics, liquidity pools, and DeFi fundamentals explained through shareable banners.",
    metaDescription: "40 free DeFi education banners — smart contracts, blockchain, liquidity explained visually. Download and share.",
    keywords: ["DeFi education banners", "blockchain education marketing", "smart contract explainer banners"],
    count: 0,
    accent: { from: "#0EA5E9", to: "#2563EB" },
  },
  {
    id: "urgency",
    label: "Urgency & FOMO",
    emoji: "⏰",
    description: "Every day you wait is compounding you're missing — urgency banners that motivate action without hype.",
    metaDescription: "34 free DeFi urgency banners — start today, every day counts, compounding starts now. Download and share.",
    keywords: ["DeFi urgency banners", "crypto FOMO marketing", "start investing today banners"],
    count: 0,
    accent: { from: "#EF4444", to: "#F97316" },
  },
  {
    id: "buyback",
    label: "Buyback & Burns",
    emoji: "🔥",
    description: "Daily buyback proof, TURBO burn mechanics, and the deflationary scarcity engine that drives token value.",
    metaDescription: "30 free DeFi buyback and burn banners — daily TURBO buyback proof, deflationary mechanics. Download and share.",
    keywords: ["DeFi buyback burn banners", "TURBO token burn", "deflationary crypto banners"],
    count: 0,
    accent: { from: "#F43F5E", to: "#EC4899" },
  },
  {
    id: "comparison",
    label: "TurboLoop vs The World",
    emoji: "⚖️",
    description: "TurboLoop vs banks, stocks, crypto, and savings accounts — side-by-side comparisons that make the case clearly.",
    metaDescription: "30 free DeFi comparison banners — TurboLoop vs banks, stocks, savings accounts. Download and share.",
    keywords: ["DeFi vs bank comparison banners", "crypto vs savings account", "TurboLoop comparison marketing"],
    count: 0,
    accent: { from: "#14B8A6", to: "#06B6D4" },
  },
  {
    id: "community",
    label: "Global Community",
    emoji: "🌍",
    description: "The TurboLoop global family — community growth, Telegram milestones, and the power of a worldwide network.",
    metaDescription: "30 free DeFi community banners — TurboLoop global family, Telegram growth, worldwide network. Download and share.",
    keywords: ["DeFi community banners", "crypto community marketing", "TurboLoop telegram community"],
    count: 0,
    accent: { from: "#A855F7", to: "#6366F1" },
  },
];

// Populate counts from manifest
for (const cat of CAMPAIGN_CATEGORIES) {
  cat.count = ALL_CAMPAIGN_CREATIVES.filter(c => c.category === cat.id).length;
}

export function getCampaignCategory(id: string): CampaignCategoryDef | undefined {
  return CAMPAIGN_CATEGORIES.find(c => c.id === id);
}

export function getCampaignCreatives(categoryId: string): CampaignCreative[] {
  return ALL_CAMPAIGN_CREATIVES.filter(c => c.category === categoryId);
}

export const TOTAL_CAMPAIGN_CREATIVES = ALL_CAMPAIGN_CREATIVES.length;
