// Banner library — two manifests merged into one array:
//   1. creatives-manifest.json — 141 legacy pillar/myth/product banners
//      (originally all English; tagged language="en" for the filter).
//   2. creatives-language-kit-manifest.json — 6-language Educational Kit
//      (65 banners × en/hi/id/fr/ar/es = 390 entries).
//
// Both are generated by scripts at upload time. Treating them as a single
// merged list keeps page code simple — filters and category counts work
// across both sources uniformly.

import manifest from "./creatives-manifest.json";
import langKitManifest from "./creatives-language-kit-manifest.json";

export type CreativePalette = { from: string; via: string; to: string };

/** Two-letter language code used for filtering. Add new codes here AND
 *  to BANNER_LANGUAGES below to surface a new tab on /creatives. */
export type BannerLanguage = "en" | "hi" | "id" | "fr" | "ar" | "es";

export const BANNER_LANGUAGES: ReadonlyArray<{
  code: BannerLanguage;
  label: string;
  flag: string;
}> = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "hi", label: "हिन्दी", flag: "🇮🇳" },
  { code: "id", label: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "ar", label: "العربية", flag: "🇸🇦" },
  { code: "es", label: "Español", flag: "🇪🇸" },
];

export type CreativeBanner = {
  slug: string;
  url: string;
  categoryId: string;
  categoryLabel: string;
  emoji: string;
  palette: CreativePalette;
  original: string;
  /** Language code. Legacy banners default to "en" via the merge logic
   *  below — the JSON itself doesn't include the field. */
  language: BannerLanguage;
  /** Headline shown above the caption (e.g. "TurboLoop is NOT a Ponzi Scheme!") */
  headline?: string;
  /** Full caption body — markdown-ish, may contain **bold** markers */
  caption?: string;
  /** Single-sentence "The Fact:" callout */
  fact?: string | null;
  /** Hashtag array (each entry includes the leading #) */
  hashtags?: string[];
  /** Visual sequence number within its category */
  visualNumber?: number | null;
};

export type CreativeCategoryDef = {
  id: string;
  label: string;
  emoji: string;
  description: string;
  count: number;
};

// Merge legacy + language-kit manifests. Legacy entries don't carry a
// `language` field — they're all English content, so we default them.
// Language-kit entries carry `language` natively (set by the upload
// script per source folder).
type RawBanner = Omit<CreativeBanner, "language"> & {
  language?: BannerLanguage;
};

const LEGACY_BANNERS: CreativeBanner[] = (manifest.items as RawBanner[]).map(
  b => ({ ...b, language: (b.language ?? "en") as BannerLanguage })
);

const LANG_KIT_BANNERS: CreativeBanner[] =
  langKitManifest.items as CreativeBanner[];

export const ALL_CREATIVES: CreativeBanner[] = [
  ...LEGACY_BANNERS,
  ...LANG_KIT_BANNERS,
];

/** Subset of ALL_CREATIVES filtered by language. Pass null/undefined for
 *  the unfiltered list. Used by /creatives page when the ?lang= param is
 *  active. */
export function bannersForLanguage(
  lang: BannerLanguage | null | undefined
): CreativeBanner[] {
  if (!lang) return ALL_CREATIVES;
  return ALL_CREATIVES.filter(b => b.language === lang);
}

/** Type guard for the search-param parsing path. */
export function isBannerLanguage(v: string | undefined): v is BannerLanguage {
  return BANNER_LANGUAGES.some(l => l.code === v);
}

const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  mythbuster: "Common DeFi myths debunked with on-chain proof.",
  product: "Deep-dive product visuals from the Turbo Loop bible.",
  quickstart: "Step-by-step starter visuals for new users.",
  "p1-math": "The math behind sustainable, transparent yield.",
  "p2-psychology": "How ownership and trust shape every deposit.",
  "p3-multiplier": "Twenty levels deep — how networks compound.",
  "p4-risk": "Risk management for serious DeFi participants.",
  "p5-velocity": "The compounding curve in motion.",
  "p6-trust": "Trustless contracts, verifiable from any browser.",
  "p7-arbitrage": "Borderless capital — global yield arbitrage.",
  "p8-legacy": "Legacy and inheritance in a permissionless world.",
  "p9-inflation": "Stablecoin yield as an inflation shield.",
  "p10-ethics": "Leadership ethics in decentralized communities.",
  "monthly-projections":
    "Monthly contribution → projected balance, in English and German. Branded social-ready visuals for $50 to $50,000 / month.",
  "hub-spotlight":
    "Premium banners promoting specific Hub pages. Perfect for sharing links.",
  "lang-kit":
    "65-banner educational kit in 6 languages — fundamentals, plans, security, and earning paths.",
};

/**
 * Distinct categories ordered for display. Each has a count of how many banners
 * fall under it. Used to render the filter pill bar.
 */
export const CREATIVE_CATEGORIES: CreativeCategoryDef[] = Array.from(
  new Map(
    ALL_CREATIVES.map((c) => [
      c.categoryId,
      {
        id: c.categoryId,
        label: c.categoryLabel,
        emoji: c.emoji,
        description: CATEGORY_DESCRIPTIONS[c.categoryId] || "",
        count: 0,
      },
    ])
  ).values()
).map((cat) => ({
  ...cat,
  count: ALL_CREATIVES.filter((c) => c.categoryId === cat.id).length,
}));

// Sort categories: language-kit leads (newest + largest set, most likely
// what visitors want), then monthly projections, hub spotlight, the
// 10 pillars, finally the original lifestyle categories.
const SORT_ORDER: string[] = [
  "lang-kit",
  "monthly-projections",
  "hub-spotlight",
  "p1-math", "p2-psychology", "p3-multiplier", "p4-risk", "p5-velocity",
  "p6-trust", "p7-arbitrage", "p8-legacy", "p9-inflation", "p10-ethics",
  "mythbuster", "product", "quickstart",
];
CREATIVE_CATEGORIES.sort((a, b) => SORT_ORDER.indexOf(a.id) - SORT_ORDER.indexOf(b.id));

/** Get banners for a given category id, or all if id === "all" */
export function bannersForCategory(id: string): CreativeBanner[] {
  if (id === "all") return ALL_CREATIVES;
  return ALL_CREATIVES.filter((c) => c.categoryId === id);
}

/** Strip markdown bold markers + trim — used for clean text output */
export function stripMarkdown(s: string): string {
  return (s || "").replace(/\*\*/g, "").replace(/\*/g, "").trim();
}

/**
 * Build the full "share text" for a banner — combines headline + caption + fact
 * + hashtags into one polished message that reads well in Telegram/X/WhatsApp.
 */
export function bannerShareText(banner: CreativeBanner): string {
  const parts: string[] = [];
  if (banner.headline) parts.push(`📌 ${stripMarkdown(banner.headline)}`);
  if (banner.caption) parts.push(stripMarkdown(banner.caption));
  if (banner.fact) parts.push(`The Fact: ${stripMarkdown(banner.fact)}`);
  const tags = (banner.hashtags && banner.hashtags.length > 0)
    ? banner.hashtags.join(" ")
    : "#TurboLoop #DeFi #BSC";
  parts.push(tags);
  return parts.join("\n\n");
}
