// /creatives/[category] — one page per campaign category.
//
// Static at build time (generateStaticParams returns the 12 ids) so
// every sub-page ships as a prerendered HTML file and the 504 images
// gain individual SEO surfaces without runtime cost.
//
// Image data comes from public/campaigns-manifest.json — generated by
// scripts/generate-campaigns-manifest.mjs from R2. The manifest also
// drives the /creatives ImageGallery JSON-LD on the parent page.

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import { promises as fs } from "node:fs";
import path from "node:path";
import { Container } from "@components/ui/Container";
import { Heading } from "@components/ui/Heading";
import { PageHero } from "@components/layout/PageHero";
import {
  CAMPAIGN_CATEGORIES,
  findCampaignCategory,
  type CampaignsManifest,
  type CampaignImage,
} from "@lib/creativesData";

const BASE_URL = "https://www.turboloop.tech";

export function generateStaticParams() {
  return CAMPAIGN_CATEGORIES.map(c => ({ category: c.id }));
}

async function loadManifest(): Promise<CampaignsManifest | null> {
  try {
    const manifestPath = path.join(
      process.cwd(),
      "public",
      "campaigns-manifest.json"
    );
    const raw = await fs.readFile(manifestPath, "utf-8");
    return JSON.parse(raw) as CampaignsManifest;
  } catch {
    return null;
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ category: string }>;
}): Promise<Metadata> {
  const { category } = await params;
  const cat = findCampaignCategory(category);
  if (!cat) return { title: "Category not found" };
  const title = `${cat.label} Marketing Banners — Free TurboLoop Creatives`;
  const url = `${BASE_URL}/creatives/${cat.id}`;
  return {
    title,
    description: cat.description,
    keywords: cat.keywords,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      title: `${cat.label} — TurboLoop Marketing Creatives`,
      description: cat.description,
      url,
    },
    twitter: {
      card: "summary_large_image",
      title: `${cat.label} — TurboLoop Marketing Creatives`,
      description: cat.description,
    },
  };
}

export default async function CampaignCategoryPage({
  params,
}: {
  params: Promise<{ category: string }>;
}) {
  const { category } = await params;
  const cat = findCampaignCategory(category);
  if (!cat) notFound();

  const manifest = await loadManifest();
  const entry = manifest?.categories.find(c => c.id === cat.id);
  const images: CampaignImage[] = entry?.images ?? [];

  // ImageGallery JSON-LD scoped to this category — gives Google a
  // structured signal that this URL surfaces a coherent gallery of
  // brand assets.
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "ImageGallery",
    name: `${cat.label} — TurboLoop Marketing Creatives`,
    description: cat.description,
    numberOfItems: images.length,
    url: `${BASE_URL}/creatives/${cat.id}`,
  };

  return (
    <main className="relative pb-12 md:pb-20">
      <script
        type="application/ld+json"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <PageHero
        eyebrow={`${cat.emoji} ${cat.label}`}
        title={`${images.length} branded banners — ready to share.`}
        subtitle={cat.description}
      />

      <Container width="wide">
        <div className="mb-6 flex items-baseline justify-between">
          <Heading tier="h2">All {cat.label} banners</Heading>
          <a
            href="/creatives"
            className="text-sm font-bold text-[var(--c-brand-cyan)] hover:underline"
          >
            ← All categories
          </a>
        </div>

        {images.length === 0 ? (
          <div className="rounded-[var(--r-lg)] border border-[var(--c-border)] bg-[var(--c-surface)] p-6 text-sm text-[var(--c-text-muted)]">
            No banners available for this category yet. Run{" "}
            <code className="text-xs">npm run campaigns:manifest</code> after
            the next R2 upload to populate this page.
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-4">
            {images.map(img => (
              <a
                key={img.filename}
                href={img.url}
                target="_blank"
                rel="noopener noreferrer"
                download={img.filename}
                title={`Open ${img.alt}`}
                className="group block rounded-[var(--r-lg)] overflow-hidden border border-[var(--c-border)] bg-[var(--c-surface)] shadow-[var(--s-sm)] hover:shadow-[var(--s-md)] transition"
              >
                <div className="relative aspect-square w-full bg-[var(--c-bg)]">
                  <Image
                    src={img.url}
                    alt={img.alt}
                    fill
                    sizes="(max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw"
                    className="object-cover group-hover:scale-[1.02] transition-transform duration-500"
                    loading="lazy"
                  />
                </div>
                <div className="p-2.5 md:p-3">
                  <div className="text-[11px] font-bold text-[var(--c-text)] line-clamp-2 leading-snug">
                    {img.title}
                  </div>
                  <div className="text-[10px] text-[var(--c-text-subtle)] mt-1 truncate">
                    {img.filename}
                  </div>
                </div>
              </a>
            ))}
          </div>
        )}
      </Container>
    </main>
  );
}
