// Root layout — wraps every page in the app.
//
// Mobile-first by design:
//   - viewport-fit=cover so safe-area insets work on phones with notches
//   - dark mode auto-applies based on system preference (CSS handles it)
//   - Geist font preloaded so the brand mark never flashes serif fallback
//   - apple-mobile-web-app meta tags for the PWA standalone install
//   - theme-color tracks the current scheme (status bar tint on Android)
//
// No client-side providers here yet — the homepage is purely static.
// When we add the tRPC client (for /apply, /submit, /admin), it gets
// wired into a "client boundary" wrapper inside the interactive routes.

import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Navbar } from "@components/layout/Navbar";
import { Footer } from "@components/layout/Footer";
import { MobileBottomCTA } from "@components/layout/MobileBottomCTA";
import { ToastProvider } from "@components/Toast";
import { CommandPalette } from "@components/CommandPalette";
import { WelcomePopup } from "@components/WelcomePopup";
import { BackToTop } from "@components/ui/BackToTop";
import { GoogleAnalytics } from "@components/analytics/GoogleAnalytics";
import { ConsentBanner } from "@components/analytics/ConsentBanner";
import { SmartNotifications } from "@components/notifications/SmartNotifications";
import { ChatWidget } from "@components/chatbot/ChatWidget";

// Build-time check: only emit the GA bootstrap (consent defaults + Script
// tags + banner) when the measurement ID is actually configured. Avoids
// noise in local dev and in preview deploys that don't set the env var.
const GA_ID = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID;

// Homepage metadata — Title/description rewritten per the May-2026 SEO
// audit to surface the protocol's actual value props (sustainable ROI,
// LP-backed, audited) and the headline figure (up to 54% in 60 days).
// Numbers verified against next-app/app/calculator/page.tsx PLANS:
//   Sprint 7d / 3% · Boost 14d / 10% · Power 30d / 24% · Ultimate 60d / 54%
export const metadata: Metadata = {
  metadataBase: new URL("https://www.turboloop.tech"),
  title: {
    default:
      "TurboLoop — DeFi Yield Farming on BSC | Sustainable ROI Protocol",
    template: "%s · Turbo Loop",
  },
  description:
    "TurboLoop generates fixed ROI per cycle from a USDC/USDT stablecoin LP, Turbo Swap fees, and Turbo Buy fees. 100% LP-locked, audited, ownership renounced. Up to 54% in 60 days, 1 USDT minimum.",
  applicationName: "TurboLoop",
  authors: [{ name: "Turbo Loop" }],
  keywords: [
    "TurboLoop",
    "TurboLoop DeFi",
    "TurboLoop Protocol",
    "DeFi yield farming",
    "BSC yield",
    "Binance Smart Chain",
    "stablecoin yield",
    "audited smart contract",
    "renounced ownership",
    "non-custodial DeFi",
  ],
  openGraph: {
    type: "website",
    siteName: "Turbo Loop",
    url: "https://www.turboloop.tech",
    title:
      "TurboLoop — DeFi Yield Farming on BSC | Sustainable ROI Protocol",
    description:
      "Fixed ROI per cycle. Real yield from USDC/USDT LP rewards + Turbo Swap fees + Turbo Buy fees. Audited, ownership renounced, 100% LP-locked. From 1 USDT.",
    images: [
      {
        // Absolute URL — the og-banner route handler now lives inside the
        // Next-app project at app/api/og-banner/route.ts (Edge runtime).
        // We use the explicit www host because the apex 307s to www and
        // some OG-preview crawlers don't follow redirects on the image URL.
        url: "https://www.turboloop.tech/api/og-banner?type=launch",
        width: 1200,
        height: 630,
        alt: "TurboLoop — sustainable DeFi yield on Binance Smart Chain.",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@TurboLoop_io",
    title:
      "TurboLoop — DeFi Yield Farming on BSC | Sustainable ROI Protocol",
    description:
      "Up to 54% flat ROI in 60 days. Audited, renounced, 100% LP-locked.",
    images: ["https://www.turboloop.tech/api/og-banner?type=launch"],
  },
  // Manifest is generated by app/manifest.ts (Next.js convention) — gives
  // Android Chrome an "Add to Home Screen" prompt with proper theme color
  // and the brand mark without us hand-maintaining a JSON file.
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "TurboLoop",
  },
  // Icons are auto-discovered from app/icon.png + app/apple-icon.png
  // (Next.js convention) — no `icons:` field needed. public/favicon.ico
  // is also auto-served at /favicon.ico for legacy crawlers. We dropped
  // the previous remote-R2-PNG approach because (a) it was 312 KB,
  // (b) Vercel image-optimizer cached the old logo for ~24h, and
  // (c) the convention files give Next.js full control over the
  // `<link rel>` tags + sizes.
  alternates: {
    canonical: "https://www.turboloop.tech/",
    // RSS auto-discovery. Browsers + feedreaders read these to surface
    // a "Subscribe" affordance. Four feeds: the unqualified /feed.xml
    // stays English (back-compat with existing subscribers);
    // /feed.de.xml, /feed.hi.xml, /feed.id.xml carry their respective
    // languages. Each feed lists only posts in its language.
    types: {
      "application/rss+xml": [
        { url: "https://www.turboloop.tech/feed.xml", title: "Turbo Loop — English" },
        { url: "https://www.turboloop.tech/feed.de.xml", title: "Turbo Loop — Deutsch" },
        { url: "https://www.turboloop.tech/feed.hi.xml", title: "Turbo Loop — हिंदी" },
        { url: "https://www.turboloop.tech/feed.id.xml", title: "Turbo Loop — Bahasa Indonesia" },
      ],
    },
  },
};

// Site-wide JSON-LD — identifies the org + the site for rich search
// snippets. Rendered once in the root layout's <head>.
//
// Three top-level entities in the @graph:
//   1. Organization — sameAs links power knowledge-panel sourcing
//   2. WebSite — declares the in-blog search action
//   3. SiteNavigationElement — explicit declaration of the 6 main
//      sections. Encourages (but does not guarantee) Google Sitelinks
//      under the brand result. Google generates sitelinks
//      algorithmically; the schema is one hint among many. The footer
//      <nav aria-label="Site sections"> below reinforces this with an
//      explicit internal link graph — the bigger of the two signals.
const SITE_JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://www.turboloop.tech/#organization",
      name: "Turbo Loop",
      // alternateName disambiguates from unrelated entities Google has
      // historically conflated this brand with (an Italian auto-parts
      // store named "TURBO LOOP" with a Google Business Profile, plus
      // a climbing-equipment brand "CAMP Turboloop"). Both "TurboLoop
      // DeFi" and "TurboLoop Protocol" are reinforced throughout the
      // site copy so the synonym set is consistent with on-page signal.
      alternateName: ["TurboLoop DeFi", "TurboLoop Protocol"],
      url: "https://www.turboloop.tech",
      // `logo` is the structured logo Google's knowledge panel reads.
      // `image` is the broader brand image — using the same R2 PNG
      // satisfies both fields. References Organization#logo by @id so
      // crawlers see they're the same asset, not duplicates.
      logo: {
        "@type": "ImageObject",
        "@id": "https://www.turboloop.tech/#logo",
        url: "https://pub-1d13f4e7ccfa4575bc04b75045f1b1b1.r2.dev/branding/turboloop-logo.png",
        contentUrl:
          "https://pub-1d13f4e7ccfa4575bc04b75045f1b1b1.r2.dev/branding/turboloop-logo.png",
        width: 549,
        height: 567,
        caption: "TurboLoop brand mark — vortex on dark.",
      },
      image: { "@id": "https://www.turboloop.tech/#logo" },
      sameAs: [
        "https://t.me/TurboLoop_Official",
        "https://t.me/TurboLoop_Chat",
        "https://x.com/TurboLoop_io",
        "https://www.youtube.com/@OfficialTurbo_Loop",
        "https://www.tiktok.com/@turboloop",
      ],
      description:
        "TurboLoop — decentralized yield protocol on Binance Smart Chain. Fixed ROI per cycle (Sprint 3% / Boost 10% / Power 24% / Ultimate 54%), 1 USDT minimum, audited and immutable smart contract with ownership permanently renounced.",
      foundingDate: "2026",
    },
    // Primary OG image as a standalone ImageObject entity. Lets Google's
    // article-snippet + image-pack crawlers pick it up explicitly
    // (in addition to inferring it from openGraph.images on each page).
    // The /api/og-banner Edge route generates this PNG dynamically;
    // the 1200×630 dimensions match what Twitter cards + Facebook
    // OG specs expect for hero previews.
    {
      "@type": "ImageObject",
      "@id": "https://www.turboloop.tech/#default-og",
      url: "https://www.turboloop.tech/api/og-banner?type=launch",
      contentUrl:
        "https://www.turboloop.tech/api/og-banner?type=launch",
      width: 1200,
      height: 630,
      caption:
        "TurboLoop — DeFi yield farming on Binance Smart Chain. Up to 54% flat ROI in 60 days.",
      representativeOfPage: true,
    },
    {
      "@type": "WebSite",
      "@id": "https://www.turboloop.tech/#website",
      url: "https://www.turboloop.tech",
      name: "Turbo Loop",
      description: "The complete DeFi ecosystem on Binance Smart Chain.",
      publisher: { "@id": "https://www.turboloop.tech/#organization" },
      inLanguage: "en",
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate:
            "https://www.turboloop.tech/blog?q={search_term_string}",
        },
        "query-input": "required name=search_term_string",
      },
    },
    // ── SiteNavigationElement (one per top-level section) ──
    // Listed in the order Google should prefer for sitelinks. Six is
    // the typical sitelinks cap; we surface our six highest-intent
    // destinations. Order matches the footer <nav> below — keep both
    // in sync so the explicit-link graph and the schema agree.
    ...[
      {
        path: "/ecosystem",
        name: "Ecosystem",
        description: "Six pillars of the TurboLoop DeFi protocol.",
      },
      {
        path: "/calculator",
        name: "Yield Calculator",
        description: "Pick a plan, set a deposit, see the projection.",
      },
      {
        path: "/security",
        name: "Security",
        description:
          "Audited by SolidityScan, ownership renounced, 100% LP locked.",
      },
      {
        path: "/events",
        name: "Events",
        description: "Global TurboLoop community meetups.",
      },
      {
        path: "/blog",
        name: "Blog",
        description: "Long-form on DeFi, yield, and the math behind it.",
      },
      {
        path: "/apply",
        name: "Apply to Earn",
        description: "Creator Star, Local Presenter, and other earn paths.",
      },
    ].map(s => ({
      "@type": "SiteNavigationElement",
      name: s.name,
      url: `https://www.turboloop.tech${s.path}`,
      description: s.description,
      isPartOf: { "@id": "https://www.turboloop.tech/#website" },
    })),
  ],
};

export const viewport: Viewport = {
  // Mobile viewport that respects the iPhone notch / Android bezels and
  // never zooms accidentally on input focus (an Android Chrome quirk).
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  // Tracks the theme — status bar on Android matches the page bg.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#0891B2" },
    { media: "(prefers-color-scheme: dark)", color: "#0F172A" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* SERVICE WORKER KILL — runs on EVERY page load, not gated by
            localStorage. The legacy Vite SPA's Workbox SW aggressively
            cached HTML and is the reason "the site looks broken on
            Brave but works on Chrome." Combined with the self-killing
            /sw.js shipped at the same path, this removes the SW for any
            user who lands here. Once cleared (no SW found), this is
            essentially a no-op — cheap to run on every visit. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  if (!('serviceWorker' in navigator)) return;
                  navigator.serviceWorker.getRegistrations().then(function (regs) {
                    if (!regs.length) return;
                    var did = false;
                    regs.forEach(function (r) {
                      r.unregister();
                      did = true;
                    });
                    if (window.caches && caches.keys) {
                      caches.keys().then(function (keys) {
                        keys.forEach(function (k) { caches.delete(k); });
                      });
                    }
                    if (did) {
                      var KEY = 'tl_sw_reloaded_at';
                      var last = Number(sessionStorage.getItem(KEY) || 0);
                      if (Date.now() - last > 30000) {
                        sessionStorage.setItem(KEY, String(Date.now()));
                        window.location.reload();
                      }
                    }
                  }).catch(function () {});
                } catch (e) {}
              })();
            `.trim(),
          }}
        />
        {/* Apply the user's saved theme synchronously, before any paint,
            so dark-mode users never see a flash of light theme. The
            script is tiny + inlined; it reads localStorage and adds the
            .dark or .light class to <html> before React hydrates. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  var stored = localStorage.getItem('turboloop_theme');
                  var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
                  var theme = stored || (prefersDark ? 'dark' : 'light');
                  document.documentElement.classList.add(theme);
                } catch (e) {}
              })();
            `.trim(),
          }}
        />
        {/* Geist font — only the 4 weights we actually use. Preloaded so
            the hero never flashes the system fallback. */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        {/* R2 CDN preconnect — saves ~150 ms on the first below-fold image. */}
        <link
          rel="preconnect"
          href="https://pub-1d13f4e7ccfa4575bc04b75045f1b1b1.r2.dev"
          crossOrigin="anonymous"
        />
        {/* <link rel="image_src"> — legacy social-image hint that
            Facebook, LinkedIn, and a handful of image-search tools
            still read in addition to og:image. Points to the canonical
            brand logo so every page in the site associates with the
            same brand-mark image, regardless of the per-page og:image.
            This is a brand-disambiguation signal: it tells image
            crawlers "every page on this domain belongs to the SAME
            entity" — load-bearing for cleaning up Google Images
            results that currently mix unrelated brands. */}
        <link
          rel="image_src"
          href="https://pub-1d13f4e7ccfa4575bc04b75045f1b1b1.r2.dev/branding/turboloop-logo.png"
        />
        {/* Site-wide structured data for search rich snippets. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(SITE_JSON_LD) }}
        />
        {/* GA4 Consent Mode v2 — sets denied defaults BEFORE gtag.js loads.
            This must be inline (not next/script with beforeInteractive),
            because beforeInteractive only works from app/layout.tsx and
            we want the dataLayer + gtag function defined before any
            other script touches them. The ConsentBanner flips these to
            granted when the user accepts; the localStorage check
            restores granted state for returning visitors silently. */}
        {GA_ID && (
          <script
            dangerouslySetInnerHTML={{
              __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                window.gtag = gtag;
                gtag('consent', 'default', {
                  ad_storage: 'denied',
                  ad_user_data: 'denied',
                  ad_personalization: 'denied',
                  analytics_storage: 'denied',
                  functionality_storage: 'granted',
                  security_storage: 'granted',
                  wait_for_update: 500,
                });
                try {
                  if (localStorage.getItem('turboloop_consent') === 'granted') {
                    gtag('consent', 'update', {
                      ad_storage: 'granted',
                      ad_user_data: 'granted',
                      ad_personalization: 'granted',
                      analytics_storage: 'granted',
                    });
                  }
                } catch (e) {}
              `.trim(),
            }}
          />
        )}
      </head>
      <body className="bg-[var(--c-bg)] text-[var(--c-text)] antialiased">
        {/* Skip link — keyboard users can jump straight to main content
            without tabbing through the entire navbar. Off-screen until
            focused, then floats into the top-left corner. */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[100] focus:px-4 focus:py-2 focus:rounded-[var(--r-md)] focus:bg-[var(--c-surface)] focus:text-[var(--c-text)] focus:shadow-[var(--s-lg)] focus:border focus:border-[var(--c-border-strong)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--c-brand-cyan)]"
        >
          Skip to content
        </a>
        <ToastProvider>
          <Navbar />
          <div id="main-content">{children}</div>
          <Footer />
          <MobileBottomCTA />
          <CommandPalette />
          <WelcomePopup />
          <BackToTop />
          <ConsentBanner />
          <SmartNotifications />
          <ChatWidget />
        </ToastProvider>
        {/* Analytics last so the gtag.js fetch never blocks first paint.
            Renders nothing if NEXT_PUBLIC_GA_MEASUREMENT_ID isn't set. */}
        <GoogleAnalytics />
      </body>
    </html>
  );
}
